### ISSUE TITLE
 Dosbox-X Wiki: Several Non-Working Demoscene Pages #5065 

### ISSUE THREAD

**Issue by MasterO2** [rderooy/dosbox-x-wiki#7]
@rderooy, all of their respective pages below return `404 Not Found`:

https://dosbox-x.com/wiki/#Guide:MS%E2%80%90DOS:demoscene:1994

http://dosbox-x.com/wiki/Guide%3AMS%E2%80%90DOS%3Ademoscene%3A1998

http://dosbox-x.com/wiki/Guide%3AMS%E2%80%90DOS%3Ademoscene%3A1999

http://dosbox-x.com/wiki/Guide%3AMS%E2%80%90DOS%3Ademoscene%3A2000

Assuming the pages in question do exist, fixing the links shouldn't take very long.

I initially posted at https://github.com/joncampbell123/dosbox-x/issues/5065, but was directed to your github repository instead.

**Comment by rderooy** [comment]
Changes made to the draft version
